### ISSUE TITLE
Import statement

### ISSUE THREAD

**Issue by adrien-prototype** [lorenzofox3/mongoose-fuzzy-search#2]
Hey Laurent

Thanks for the great work !

Sorry for that simple question but is there an alternative to using : `import fuzzy from 'mongoose-fuzzy-search'`?
What can I do to use it with require ? Because this way I get the error "SyntaxError: Cannot use import statement outside a module" and if do "const fuzzy = require"mongoose-fuzzy-search" I get another error "syntax error export default plugin".

I know I could use "type: module" in my package.json but then I'd have to change all my other imports everywhere.

Do you have an idea on what I could do ?

Thanks a lot :)

**Comment by lorenzofox3** [comment]
What version of node are you using ? 

I have no issue on Node v14.14.0
<img width="985" alt="Screenshot 2020-11-01 at 14 43 15" src="https://user-images.githubusercontent.com/2402022/97804516-ca2f7000-1c50-11eb-891e-260fc75b62f0.png">

**Comment by adrien-prototype** [comment]
Thank you it's working with that node version 👍
